[build]
  publish = "."

[[headers]]
  for = "/pages/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/pages-data.js"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"
